name: Release LIM WAF

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Build Binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/lim-waf-linux-amd64 -ldflags="-X main.Version=${{ github.ref_name }} -s -w" ./cmd/lim-waf
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/lim-waf-linux-amd64
          generate_release_notes: true
